package boggle;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

public class Dictionary {

    private ArrayList<String> dict;

    /**
     * Constructor
     *
     * @param fileName the file to generate the dictionary from
     * @throws FileNotFoundException
     */
    public Dictionary(String fileName) throws FileNotFoundException {
        dict = generateDict(fileName);
    }

    private ArrayList<String> generateDict(String fileName) throws FileNotFoundException {
        File dictFile = new File("dict.txt");
        Scanner dictScanner = new Scanner(dictFile);
        // validien sanojen sanakirja
        ArrayList<String> dict = new ArrayList<>();
        while (dictScanner.hasNext()) {
            dict.add(dictScanner.next());
        }
        dictScanner.close();
        return dict;
    }

    /**
     * Checks if the word generated by a selection of tiles is valid.
     *
     * @param tiles the list of tiles
     * @return whether the word is valid
     */
    public boolean isValidWord(ArrayList<Main.Tile> tiles) {
        String word = "";
        for (Main.Tile tile : tiles) {
            word += tile.getLetter();
        }
        word = word.toLowerCase();
        return (dict.indexOf(word) != -1);
    }
}
